### ISSUE TITLE
Create a minimal logo for the app.

### ISSUE THREAD

**Issue by yankeexe** [yankeexe/timezones-cli#1]
Create a minimal logo for the app with a CLI icon and globe in there maybe. 
Open for discussion on this, just @yankeexe  me here.

**Comment by lucid-dreem** [comment]
Hey, I'd love to help out @yankeexe ... are there guidelines for color codes or anything?

**Comment by yankeexe** [comment]
Hey @lucid-dreem  just something flat with minimal colors, not too colorful. I guess you can start with the idea of a CLI as a background with globe or a flat map to represent time zones. You can get creative with it 🙂

**Comment by udz-codes** [comment]
Is this assigned ? Can I work on it ?

**Comment by yankeexe** [comment]
Hey @lucid-dreem have you started working on this issue?

**Comment by udz-codes** [comment]
> Hey @lucid-dreem have you started working on this issue?   

Can you assign it to me ? and also let me know where should I add the logo in PR ?

**Comment by yankeexe** [comment]
Hey @udz-codes I have assigned you for this issue. 🙂 
You can add it on the README, take this repo for reference: 
https://github.com/yankeexe/good-first-issues

**Comment by udz-codes** [comment]
> Hey @udz-codes I have assigned you for this issue. 🙂
> You can add it on the README, take this repo for reference:
> https://github.com/yankeexe/good-first-issues

I am on it 🦾.

**Comment by udz-codes** [comment]
> Hey @udz-codes I have assigned you for this issue. 🙂 
> You can add it on the README, take this repo for reference: 
> https://github.com/yankeexe/good-first-issues

Hey @yankeexe , I have made the PR. Please check it out and let me know if you would like any changes.
